In [2]:
import xml.etree.ElementTree as ET
import numpy as np

In [3]:
tree = ET.parse('../cam_extri.xml')
root = tree.getroot()

In [4]:
root.tag

'document'

In [5]:
root.attrib

{'version': '1.5.0'}

In [6]:
for child in root:
    print(child.tag, child.attrib)

chunk {'label': 'Chunk 1', 'enabled': 'true'}


In [7]:
[elem.tag for elem in root.iter()]

['document',
 'chunk',
 'sensors',
 'sensor',
 'resolution',
 'property',
 'bands',
 'band',
 'band',
 'band',
 'data_type',
 'calibration',
 'resolution',
 'f',
 'cx',
 'cy',
 'k1',
 'k2',
 'k3',
 'p1',
 'p2',
 'calibration',
 'resolution',
 'f',
 'cx',
 'cy',
 'k1',
 'k2',
 'k3',
 'p1',
 'p2',
 'covariance',
 'params',
 'coeffs',
 'black_level',
 'sensitivity',
 'components',
 'component',
 'region',
 'center',
 'size',
 'R',
 'partition',
 'partition',
 'partition',
 'camera_ids',
 'partition',
 'camera_ids',
 'partition',
 'partition',
 'camera_ids',
 'partition',
 'camera_ids',
 'partition',
 'camera_ids',
 'partition',
 'partition',
 'camera_ids',
 'partition',
 'camera_ids',
 'partition',
 'camera_ids',
 'cameras',
 'camera',
 'transform',
 'camera',
 'transform',
 'rotation_covariance',
 'location_covariance',
 'camera',
 'transform',
 'rotation_covariance',
 'location_covariance',
 'camera',
 'transform',
 'rotation_covariance',
 'location_covariance',
 'camera',
 'transform',


# Elements of our interest

## Intrinsics

```xml
        <calibration type="fisheye" class="adjusted">
          <resolution width="3840" height="2160"/>
          <f>1754.6897939777334</f>
          <cx>2.7697400464221538</cx>
          <cy>-4.5177431564786428</cy>
          <k1>0.088258133463634952</k1>
          <k2>-0.030144145083343458</k2>
          <k3>0.0045997221237297093</k3>
          <p1>0.00023298827445598797</p1>
          <p2>0.0003635565877202342</p2>
        </calibration>
```

In [8]:
for cali in root.iter('calibration'):
    if cali.attrib['class'] == 'adjusted':
        res = cali.find('resolution')
        width = res.attrib['width']
        height = res.attrib['height']

        f = float(cali.find('f').text)
        cx = float(cali.find('cx').text)
        cy = float(cali.find('cy').text)
        k1 = float(cali.find('k1').text)
        k2 = float(cali.find('k2').text)
        k3 = float(cali.find('k3').text)
        p1 = float(cali.find('p1').text)
        p2 = float(cali.find('p2').text)

        print("f = ", f)
        print("cx = ", cx)
        print("cy = ", cy)
        print("k1 = ", k1)
        print("k2 = ", k2)
        print("k3 = ", k3)

        intrinsic = np.array([[f,   0.0, cx,  0.0],
                              [0.0, f,   cy,  0.0],
                              [0.0, 0.0, 1.0, 0.0],
                              [0.0, 0.0, 0.0, 1.0]])

print("width = ", width)
print("height = ", height)
print("intrinsic = ", intrinsic)


f =  1754.6897939777334
cx =  2.7697400464221538
cy =  -4.517743156478643
k1 =  0.08825813346363495
k2 =  -0.030144145083343458
k3 =  0.004599722123729709
width =  3840
height =  2160
intrinsic =  [[ 1.75468979e+03  0.00000000e+00  2.76974005e+00  0.00000000e+00]
 [ 0.00000000e+00  1.75468979e+03 -4.51774316e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Extrinsics

Each of the 855 pictures has a corresponding extrinsic

```xml
    <cameras next_id="855" next_group_id="0">
      <camera id="0" sensor_id="0" component_id="0" label="000001">
        <transform>9.9345498363011719e-01 7.3678764920067086e-02 8.7284793064630953e-02 1.2970027462098785e-01 7.3722842385372050e-02 -9.9727505145529849e-01 2.7229130453602646e-03 -2.9441835077913491e-02 8.7247567364961823e-02 3.7297915068393861e-03 -9.9617967789159989e-01 5.4636722036699593e-02 0 0 0 1</transform>
      </camera>
      <camera id="1" sensor_id="0" component_id="0" label="000002">
        <transform>9.9254510458662226e-01 8.4963461686590358e-02 8.7380922056031526e-02 1.2375803980440560e-01 8.4893467489844388e-02 -9.9637976495185165e-01 4.5236237733738650e-03 -3.1247405729306583e-02 8.7448925314618356e-02 2.9281688345426183e-03 -9.9616470088464526e-01 5.4621388630770387e-02 0 0 0 1</transform>
        <rotation_covariance>2.0459090302337530e-09 -4.0041143381280146e-11 2.7090912875657807e-10 -4.0041143381280172e-11 1.5940534352638429e-09 -2.9954499013381573e-10 2.7090912875657807e-10 -2.9954499013381573e-10 1.5431559391006892e-09</rotation_covariance>
        <location_covariance>2.9151727231509507e-08 1.7153358969527433e-10 1.3933677286600782e-09 1.7153358969527433e-10 3.0507804508404932e-08 1.3692507079945613e-09 1.3933677286600782e-09 1.3692507079945613e-09 2.6591987184538840e-08</location_covariance>
      </camera>
      ...
      <camera id="854" sensor_id="0" component_id="0" label="000855">
        <transform>7.9788189029392842e-01 5.0900136149808173e-01 -3.2295836130078170e-01 3.0921065676214377e+00 2.3833205917180419e-01 -7.5846321547455542e-01 -6.0657347480987411e-01 -1.2801118058602612e-01 -5.5369876170343257e-01 4.0700265940789238e-01 -7.2647540668833965e-01 -4.2767110644642647e-01 0 0 0 1</transform>
        <rotation_covariance>5.5888960285209149e-09 7.1397114894418307e-10 -7.3113405526063045e-10 7.1397114894418328e-10 5.9476552896083920e-09 -1.6994870899039804e-09 -7.3113405526063066e-10 -1.6994870899039806e-09 3.6209192595749333e-09</rotation_covariance>
        <location_covariance>2.2256325544172061e-08 -7.1198725275460325e-10 1.1364580396689321e-09 -7.1198725275460325e-10 4.5109972266107705e-08 -7.0902251503035694e-10 1.1364580396689321e-09 -7.0902251503035694e-10 6.1017397207754107e-08</location_covariance>
      </camera>
    </cameras>

```

In [9]:
for camera in root.iter('camera'):
    print(camera.attrib)

{'id': '0', 'sensor_id': '0', 'component_id': '0', 'label': '000001'}
{'id': '1', 'sensor_id': '0', 'component_id': '0', 'label': '000002'}
{'id': '2', 'sensor_id': '0', 'component_id': '0', 'label': '000003'}
{'id': '3', 'sensor_id': '0', 'component_id': '0', 'label': '000004'}
{'id': '4', 'sensor_id': '0', 'component_id': '0', 'label': '000005'}
{'id': '5', 'sensor_id': '0', 'component_id': '0', 'label': '000006'}
{'id': '6', 'sensor_id': '0', 'component_id': '0', 'label': '000007'}
{'id': '7', 'sensor_id': '0', 'component_id': '0', 'label': '000008'}
{'id': '8', 'sensor_id': '0', 'component_id': '0', 'label': '000009'}
{'id': '9', 'sensor_id': '0', 'component_id': '0', 'label': '000010'}
{'id': '10', 'sensor_id': '0', 'component_id': '0', 'label': '000011'}
{'id': '11', 'sensor_id': '0', 'component_id': '0', 'label': '000012'}
{'id': '12', 'sensor_id': '0', 'component_id': '0', 'label': '000013'}
{'id': '13', 'sensor_id': '0', 'component_id': '0', 'label': '000014'}
{'id': '14', 'se

In [10]:
for ref in root.iter('reference'):
    print(ref.text)

LOCAL_CS["Local Coordinates (m)",LOCAL_DATUM["Local Datum",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]


In [11]:
root.iter('camera')

In [12]:
print(root[0].tag)
print(len(root[0]))


chunk
7


In [13]:
for child in root[0]:
    print(child.tag)

sensors
components
cameras
reference
region
settings
meta


In [14]:
for camera in root.iter('camera'):
    print(camera.attrib)
    # print(camera.attrib['id'])


{'id': '0', 'sensor_id': '0', 'component_id': '0', 'label': '000001'}
{'id': '1', 'sensor_id': '0', 'component_id': '0', 'label': '000002'}
{'id': '2', 'sensor_id': '0', 'component_id': '0', 'label': '000003'}
{'id': '3', 'sensor_id': '0', 'component_id': '0', 'label': '000004'}
{'id': '4', 'sensor_id': '0', 'component_id': '0', 'label': '000005'}
{'id': '5', 'sensor_id': '0', 'component_id': '0', 'label': '000006'}
{'id': '6', 'sensor_id': '0', 'component_id': '0', 'label': '000007'}
{'id': '7', 'sensor_id': '0', 'component_id': '0', 'label': '000008'}
{'id': '8', 'sensor_id': '0', 'component_id': '0', 'label': '000009'}
{'id': '9', 'sensor_id': '0', 'component_id': '0', 'label': '000010'}
{'id': '10', 'sensor_id': '0', 'component_id': '0', 'label': '000011'}
{'id': '11', 'sensor_id': '0', 'component_id': '0', 'label': '000012'}
{'id': '12', 'sensor_id': '0', 'component_id': '0', 'label': '000013'}
{'id': '13', 'sensor_id': '0', 'component_id': '0', 'label': '000014'}
{'id': '14', 'se

In [15]:
import numpy as np

In [16]:
for camera in root.iter('camera'):
    transform_str = camera[0].text
    transform_list = transform_str.split()
    transform_ctow = np.array(transform_list, dtype='float').reshape((4,4))
    extrinsic = np.linalg.inv(transform_ctow)
    print(extrinsic)
    
    break

[[ 0.99345498  0.07372284  0.08724757 -0.13144777]
 [ 0.07367876 -0.99727505  0.00372979 -0.03912155]
 [ 0.08728479  0.00272291 -0.99617968  0.0431873 ]
 [ 0.          0.          0.          1.        ]]


In [17]:
print(eval('9.9345498363011719e-01'))
print(eval('7.3678764920067086e-02'))

0.9934549836301172
0.07367876492006709


In [18]:
transform_list = ['9.9345498363011719e-01', '7.3678764920067086e-02', '8.7284793064630953e-02', '1.2970027462098785e-01', '7.3722842385372050e-02', '-9.9727505145529849e-01', '2.7229130453602646e-03', '-2.9441835077913491e-02', '8.7247567364961823e-02', '3.7297915068393861e-03', '-9.9617967789159989e-01', '5.4636722036699593e-02', '0', '0', '0', '1']
transform_ctow = np.array(transform_list, dtype='float').reshape((4,4))
print(transform_ctow)
print(transform_ctow.dtype)

[[ 0.99345498  0.07367876  0.08728479  0.12970027]
 [ 0.07372284 -0.99727505  0.00272291 -0.02944184]
 [ 0.08724757  0.00372979 -0.99617968  0.05463672]
 [ 0.          0.          0.          1.        ]]
float64


In [24]:
for camera in root.iter('camera'):
    image_id = int(camera.attrib['id']) + 1 # Used to match the image
    
    # Get camera extrinsic
    transform_str = camera[0].text
    transform_str = camera[0].text
    transform_list = transform_str.split()
    transform_ctow = np.array(transform_list, dtype='float').reshape((4,4))
    extrinsic = np.linalg.inv(transform_ctow)
    print(extrinsic.tolist())
    break

    
    

[[0.9934549836301189, 0.07372284238537212, 0.08724756736496192, -0.1314477695199279], [0.07367876492006721, -0.9972750514552992, 0.0037297915068389936, -0.039121547217946535], [0.08728479306463108, 0.0027229130453598704, -0.9961796778916003, 0.04318729808566654], [0.0, 0.0, 0.0, 1.0]]


In [25]:
import random

In [26]:
sampled_numbers = random.sample(range(1, 856), 50)
print(sampled_numbers)

[797, 4, 303, 210, 207, 684, 93, 402, 215, 814, 460, 453, 350, 501, 371, 6, 749, 98, 301, 584, 431, 588, 141, 444, 408, 468, 314, 571, 823, 360, 505, 714, 340, 21, 778, 271, 585, 606, 579, 597, 733, 321, 623, 78, 347, 376, 413, 627, 177, 626]
